name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 13.x, 14.x ]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build:h5
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: dist/h5
          commit_message: ${{ github.event.head_commit.message }}
          # keep_files: false
          force_orphan: true
